#!/bin/bash
SSH_DIR=/var/lib/postgresql/.ssh
PG_DATA_DIR=/var/lib/postgresql/9.3/main
PG_CONF_DIR=/etc/postgresql/9.3/main
PG_CONF=$PG_CONF_DIR/postgresql.conf
PG_HBA=$PG_CONF_DIR/pg_hba.conf

#CONFIGURE SSH
if [ ! -d $SSH_DIR ]; then
	mkdir -p $SSH_DIR

	case $ROLE in
		MASTER1)
			cp /tmp/.ssh/1/id_rsa* $SSH_DIR
		;;
		MASTER2)
			cp /tmp/.ssh/2/id_rsa* $SSH_DIR
		;;
		SLAVE1)
			cp /tmp/.ssh/1/authorized_keys2 $SSH_DIR
		;;
		SLAVE2)
			cp /tmp/.ssh/2/authorized_keys2 $SSH_DIR
		;;
	esac
	
	chown -R postgres:postgres $SSH_DIR
fi

#CONFIGURE postgresql
if [ ! -f /pg_config_done ]; then
	sed -i "s/#wal_level = minimal/wal_level = hot_standby/g" $PG_CONF
	sed -i "s/#max_wal_senders = 0/max_wal_senders = 3/g" $PG_CONF
	sed -i "s/#checkpoint_segments = 3/checkpoint_segments = 8/g" $PG_CONF
	sed -i "s/#wal_keep_segments = 0/wal_keep_segments = 8/g" $PG_CONF
	
	case $ROLE in
		MASTER1)
			sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '192.168.10.20'/g" $PG_CONF
			echo 'host  replication  postgres  192.168.10.21/24  trust' >> $PG_HBA
			echo 'host  replication  postgres  192.168.10.22/24  trust' >> $PG_HBA
		;;
		MASTER2)
			sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '192.168.20.20'/g" $PG_CONF
			echo 'hostssl  replication  postgres  192.168.20.21/24  trust' >> $PG_HBA
			echo 'hostssl  replication  postgres  192.168.20.22/24  trust' >> $PG_HBA
		;;
		SLAVE1|SLAVE2)
			sed -i "s/#hot_standby = off/hot_standby = on/g" $PG_CONF
			/bin/su postgres -c "rm -rf /var/lib/postgresql/9.3/main"
		;;
	esac
	case $ROLE in
		SLAVE1)
			/bin/su postgres -c "pg_basebackup -h 192.168.10.20 -D /var/lib/postgresql/9.3/main -U postgres -v"
		;;
		SLAVE2)
			/bin/su postgres -c "pg_basebackup -h 192.168.20.20 -D /var/lib/postgresql/9.3/main -U postgres -v"
		;;
	esac
	case $ROLE in
		SLAVE1)
			sh /tmp/scripts/make_recovery_1
		;;
		SLAVE2)
			sh /tmp/scripts/make_recovery_2
		;;
	esac
fi
touch /pg_config_done
#Starting ssh daemon
if [ ! -d /var/run/sshd ]; then
	mkdir -p /var/run/sshd
fi
/usr/sbin/sshd -D
#Starting Postgres
/bin/su postgres -c "/usr/lib/postgresql/9.3/bin/postgres -D /var/lib/postgresql/9.3/main -c config_file=/etc/postgresql/9.3/main/postgresql.conf"
