#!/bin/bash
PIPE=helper_scripts/pipework
PROJECT=$PWD/php-fpm-data/laravel/scs-data
DB_EXIST="/usr/bin/psql -x -h 192.168.10.20 -p 5432 -U postgres -l" | grep scs-data | wc -l

if [ $DB_EXIST=="0" ];
then
	/usr/bin/psql -x -h 192.168.10.20 -p 5432 -U postgres -c 'CREATE DATABASE "scs-data" OWNER postgres;'
	echo "Creating database"
else
	echo "Database already exist"
fi

#MIGRATE
php $PROJECT/artisan migrate
#SEED
php $PROJECT/artisan db:seed

sudo $PIPE bush1 $(docker run -d -expose 9000 -v $PROJECT:/var/www pinnokio/php-fpm:data) 192.168.10.10/24
echo "Php-fpm data container 1 of 2 started"

sudo $PIPE bush1 $(docker run -d -expose 9000 -v $PROJECT:/var/www pinnokio/php-fpm:data) 192.168.10.11/24
echo "Php-fpm data container 2 of 2 started"