#!/bin/bash
PIPE=helper_scripts/pipework

sudo $PIPE bush1 $(docker run -d -expose 9000 pinnokio/php-fpm:data) 192.168.10.10/24
echo "Php-fpm data container 1 of 2 started"

sudo $PIPE bush1 $(docker run -d -expose 9000 pinnokio/php-fpm:data) 192.168.10.11/24
echo "Php-fpm data container 2 of 2 started"
