#!/bin/bash
PIPE=helper_scripts/pipework
#PORTMAPPING MUST BE DELETED UFTER DEBUG
sudo $PIPE bush2 $(docker run -d -expose 80 -p 81:80 -e SERVER=2 pinnokio/nginx:base) 192.168.20.1/24
echo "Nginx of AUTH group started"
