#!/bin/bash
PG_IMG=pinnokio/postgresql:base
PIPE=helper_scripts/pipework

sudo $PIPE bush1 $(docker run -d -expose 22 -expose 5432 -e ROLE=MASTER1 $PG_IMG) 192.168.10.20/24
echo "Master of DATA group started"
sleep 30

sudo $PIPE bush1 $(docker run -d -expose 22 -expose 5432 -e ROLE=SLAVE1 $PG_IMG) 192.168.10.21/24
echo "Slave 1 of DATA group started"
sleep  60

sudo $PIPE bush1 $(docker run -d -expose 22 -expose 5432 -e ROLE=SLAVE1 $PG_IMG) 192.168.10.22/24
echo "Slave 2 of DATA group  started"
